// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl5Xz4WHhysdsHZUKWN0V9NuWYHLZemzk',
    appId: '1:362945118136:web:beb15b4edb954d2561594d',
    messagingSenderId: '362945118136',
    projectId: 'timoti-mall-5abb3',
    authDomain: 'timoti-mall-5abb3.firebaseapp.com',
    storageBucket: 'timoti-mall-5abb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9nEkI7R8HsvO6CUAw9v5Buvm9Gvc5CtY',
    appId: '1:362945118136:android:c30b6a247f94e8e361594d',
    messagingSenderId: '362945118136',
    projectId: 'timoti-mall-5abb3',
    storageBucket: 'timoti-mall-5abb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl0efHF4hQnbmz1qDE8jU-5ovwf8tUPAY',
    appId: '1:362945118136:ios:5b084b2396f970b661594d',
    messagingSenderId: '362945118136',
    projectId: 'timoti-mall-5abb3',
    storageBucket: 'timoti-mall-5abb3.appspot.com',
    iosClientId: '362945118136-0ljndtgvdvi6203ijveic08eo8s9stdc.apps.googleusercontent.com',
    iosBundleId: 'com.innotia.timoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl0efHF4hQnbmz1qDE8jU-5ovwf8tUPAY',
    appId: '1:362945118136:ios:2f85337b4fefccd761594d',
    messagingSenderId: '362945118136',
    projectId: 'timoti-mall-5abb3',
    storageBucket: 'timoti-mall-5abb3.appspot.com',
    iosClientId: '362945118136-dh4gi4ma36boib4ub7meai6lcqs5ll5u.apps.googleusercontent.com',
    iosBundleId: 'com.innotia.timoti.RunnerTests',
  );
}
